services:
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: chat
      TZ: 'Asia/Shanghai'
      PGTZ: 'Asia/Shanghai'
